#!/bin/bash 
# An incomplete apt-get to pacman translator.

function ask #("commandline")
{
  read -p "Run '$@' y/n ? " answer
  case $answer in
    [Yy]) 
      eval $@
      ;;
    *) 
      echo "Aborted."
      exit 1
  esac
}

case $1 in
  install)
    shift 1
    ask "pacman -S $@"
  ;;
  remove)
    shift 1
    ask "pacman -Rc $@"
  ;;
  autoremove)
    ask "pacman -Qdtq | pacman -Rs -"
  ;;
  update)
    echo Partial upgrades are unsupported 
    echo Do a full upgrade instead: pacman -Syu or apt-get upgrade
    exit 0
  ;;
  upgrade)
    ask "pacman -Syu"
  ;;
  *)
    echo "Usage: apt-get {install|remove|autoremove|upgrade} ..."
    exit 1
esac
